version: 2.1 

 

jobs: 

  build-and-test:  

    machine: l

      image: ubuntu-2004:202104-01 

        

    steps: 

      - checkout 

      - run: make deps 

      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test 

 